# Generated by Django 2.2.6 on 2019-11-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerData',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recency', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('monetary', models.IntegerField(null=True)),
            ],
        ),
    ]
