# Generated by Django 2.2.6 on 2019-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfm_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='customer_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
