# Generated by Django 2.2.6 on 2019-11-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfm_model', '0004_auto_20191124_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutToSleep',
        ),
        migrations.DeleteModel(
            name='atRisk',
        ),
        migrations.DeleteModel(
            name='cantLoseThem',
        ),
        migrations.DeleteModel(
            name='champions',
        ),
        migrations.DeleteModel(
            name='customersNeedAttention',
        ),
        migrations.DeleteModel(
            name='hibernating',
        ),
        migrations.DeleteModel(
            name='lost',
        ),
        migrations.DeleteModel(
            name='loyalCustomers',
        ),
        migrations.DeleteModel(
            name='potentialLoyalist',
        ),
        migrations.DeleteModel(
            name='promising',
        ),
        migrations.DeleteModel(
            name='recentCustomers',
        ),
    ]
